=== Comp4711-lab7/xml-lab-7/application/data/timetable.dtd
<!ELEMENT schedule (year, term, set, (days|courses|periods))>
<!ELEMENT periods (timeslot*)>



<!ELEMENT year (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT set (#PCDATA)>



<!ELEMENT daysofweek (day*) >
<!ELEMENT day (booking*)>
<!ATTLIST day name CDATA #REQUIRED>


<!ELEMENT courses (course*)>
<!ELEMENT course (booking*)>
<!ATTLIST course name CDATA #REQUIRED>





<!ELEMENT timeslot (booking*)>

<!ATTLIST timeslot time CDATA #REQUIRED>
<!ELEMENT booking (day?, course?, instructor, building, room, type)>
<!ATTLIST booking day CDATA #IMPLIED>

<!ELEMENT day (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT type (#PCDATA)>

=== Comp4711-lab7/xml-lab-7/application/data/timetable_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE schedule SYSTEM "timetable.dtd">
<schedule>
    <periods>
        <timeslot time="12:30-1:30">
            <booking day="Monday">
                <course>Operating Systems</course>
                <instructor>Mirela Gutica</instructor>
                <building>sw1</building>
                <room>1205</room>
                <type>lecture</type>
            </booking>
            <booking day="Tuesday">
                <course>Computer Graphics</course>
                <instructor>Brenda Fine</instructor>
                <building>sw5</building>
                <room>1850</room>
                <type>lecture</type>
            </booking>
            <booking day="Thursday">
                <course>Operating Systems</course>
                <instructor>Mirela Gutica</instructor>
                <building>sw3</building>
                <room>1710</room>
                <type>lecture</type>
            </booking>
        </timeslot>      
    </periods>
    
    
    
    <courses>
        <course name="BLAW3600">
            <booking>
                <day>Monday</day>
                <time>9:30-11:20</time>
                <building>SW1</building>
                <room>4785</room>
                <instructor>Catherine Ryan</instructor>
                <type>Lab</type>
            </booking> 
    </courses>
</schedule>

=== Comp4711-lab7/xml-lab-7/application/data/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "timetable.dtd">
<!--
    Document   : courses.xml
    Description:
        Courses in Winter 2015 CST Set 4S Schedule
-->
<schedule>
    <year>2016</year>
    <term>Winter</term>
    <set>4S</set>

    <courses>
        <course name="BLAW3600">
            <booking time="9:30 - 11:20">
                <dayofweek>Monday</dayofweek>
                <instructor>Catherine Ryan</instructor>
                <building>SW1</building>
                <room>4785</room>
                <type>Lab</type>
            </booking>
            <booking time="8:30 - 10:20">
                <dayofweek>Friday</dayofweek>
                <instructor>Catherine Ryan</instructor>
                <building>SW5</building>
                <room>1840</room>
                <type>Lecture</type>
            </booking>
        </course>
        <course name="COMP4735">
            <booking time="11:20 - 12:20">
                <dayofweek>Monday</dayofweek>
                <instructor>Mirela Gutica</instructor>
                <building>SW1</building>
                <room>1205</room>
                <type>Lecture</type>
            </booking>
            <booking time="12:30 - 14:20">
                <dayofweek>Monday</dayofweek>
                <instructor>Mirela Gutica</instructor>
                <building>SE12</building>
                <room>320</room>
                <type>lab</type>
            </booking>
            <booking time="13:30 - 14:20">
                <dayofweek>Wednesday</dayofweek>
                <instructor>Mirela Gutica</instructor>
                <building>SW1</building>
                <room>1205</room>
                <type>lecture</type>
            </booking>
            <booking time="11:30 - 12:20">
                <dayofweek>Thursday</dayofweek>
                <instructor>Mirela Gutica</instructor>
                <building>SW3</building>
                <room>1710</room>
                <type>lecture</type>
            </booking>
        </course>
        <course name="COMP4977">
            <booking time="8:30 - 10:20">
                <dayofweek>Tuesday</dayofweek>
                <instructor>D'arcy Smith</instructor>
                <building>SE12</building>
                <room>325</room>
                <type>seminar</type>
            </booking>
            <booking time="2:30 - 5:20">
                <dayofweek>Friday</dayofweek>
                <instructor>D'arcy Smith</instructor>
                <building>SE12</building>
                <room>325</room>
                <type>seminar</type>
            </booking>
        </course>
        <course name="COMP4560">
            <booking time="11:30 - 12:20">
                <dayofweek>Tuesday</dayofweek>
                <instructor>Brenda Fine</instructor>
                <building>SW5</building>
                <room>1850</room>
                <type>Lecture</type>
            </booking>
            <booking time="3:30 - 5:20">
                <dayofweek>Tuesday</dayofweek>
                <instructor>Joseph Lo</instructor>
                <building>SE12</building>
                <room>320</room>
                <type>lab</type>
            </booking>
            <booking time="12:30 - 1:20">
                <dayofweek>Friday</dayofweek>
                <instructor>Brenda Fine</instructor>
                <building>SW3</building>
                <room>1750</room>
                <type>lecture</type>
            </booking>
        </course>
        <course name="COMP4711">
            <booking time="14:30 - 15:20">
                <dayofweek>Tuesday</dayofweek>
                <instructor>Jim Parry</instructor>
                <building>SW1</building>
                <room>1840</room>
                <type>Lecture</type>
            </booking>
            <booking time="9:30 - 11:20">
                <dayofweek>Wednesday</dayofweek>
                <instructor>Jim Parry</instructor>
                <building>SE12</building>
                <room>320</room>
                <type>lab</type>
            </booking>
        </course>
        <course name="COMP4976">
            <booking time="8:30 - 10:20">
                <dayofweek>Thursday</dayofweek>
                <instructor>Medhat Elmasry</instructor>
                <building>SE12</building>
                <room>308</room>
                <type>Seminar</type>
            </booking>
            <booking time="12:30 - 1:20">
                <dayofweek>Thursday</dayofweek>
                <instructor>Medhat Elmasry</instructor>
                <building>SE12</building>
                <room>308</room>
                <type>Seminar</type>
            </booking>
            <booking time="10:30 - 12:20">
                <dayofweek>Friday</dayofweek>
                <instructor>Medhat Elmasry</instructor>
                <building>SE12</building>
                <room>308</room>
                <type>Seminar</type>
            </booking>
        </course>
    </courses>
</schedule>
